
export const READY_STATE_MAP = {
	0: 'HAVE_NOTHING',
	1: 'HAVE_METADATA',
	2: 'HAVE_CURRENT_DATA',
	3: 'HAVE_FUTURE_DATA',
	4: 'HAVE_ENOUGH_DATA',
};

export const NETWORK_STATE_MAP = {
	0: 'NETWORK_EMPTY',
	1: 'NETWORK_IDLE',
	2: 'NETWORK_LOADING',
	3: 'NETWORK_NO_SOURCE',
};

export const ERROR_CODE_MAP = {
	1: 'MEDIA_ERR_ABORTED',
	2: 'MEDIA_ERR_NETWORK',
	3: 'MEDIA_ERR_DECODE',
	4: 'MEDIA_ERR_SRC_NOT_SUPPORTED',
};
